replace_0=p-                                    <p:graphicImage value="images/pdf.png" />\n
replace_1=p-                                    <p:graphicImage value="/images/excel_icon.png" />\n
replace_2=p-getCombinedTheoryMarkWithAbsentLabel
replace_3=p-and
replace_4=p-fourthGradingPeriodName
replace_5=p-foruthGradingPeriodName
replace_6=p-300
replace_7=p-finalGradeAndNg
replace_8=p- 
replace_9=p-subReport3
search_0=mLw-setCreateUpdateCommonParameters
search_1=mLw-<i class="fas fa-file-pdf me-2"></i>\n                                                        <span class="h6 mb-0">Export to PDF</span>
search_2=mLw-<i class="fas fa-file-excel me-2"></i>\n                                                        <span class="h6 mb-0">Export to Excel</span>
search_3=MLw-transient="true"
search_4=mLw-tab-
search_5=MLw-getCombinedTheoryMarkWithAbsentdLabel
search_6=MLw-required-field
search_7=mLw-click
search_8=mLw-visibility
search_9=mLw-event
