replace_0=p- 
replace_1=p-.ui-inputfield
replace_2=p-and
replace_3=p-attendanceSpecialHolidayController
replace_4=p-attendanceSpecialDaysHolidayController
replace_5=p-attendanceDeviceCommandDto
replace_6=p-attendanceDeviceCommandController
replace_7=p-deviceSelect
replace_8=p-frmCommandHistory
replace_9=p-attendanceWeekendHolidayController
search_0=mLw-sendemail
search_1=mLw-sendEmailToOrganizationAdminForFreePackage
search_2=mLw-fileupload
search_3=mLw-ui-selectonemenu
search_4=mLw-panFile
search_5=mLw-tempLocation
search_6=mLw-getfilename
search_7=mLw-collegeLogoFileName
search_8=mLw-uploadtype
search_9=mLw-setPhotoUrl
