com.akshamalainfotech\:admin\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/admin/
com.akshamalainfotech\:akshamala-erp-ear\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/akshamala-erp-ear/
com.akshamalainfotech\:akshamala-erp-EJB\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-inventory/akshamala-erp-ejb/
com.akshamalainfotech\:akshamala-erp-ejb\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/akshamala-erp-ejb/
com.akshamalainfotech\:akshamala-erp-Entity\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/akshamala-erp-Entity/
com.akshamalainfotech\:akshamala-erp\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/
com.akshamalainfotech\:mavenproject1\:1.0-SNAPSHOT=file:/home/sandip/NetBeansProjects/mavenproject1/
com.akshamalainfotech\:student\:1.0-SNAPSHOT=file:/home/sandip/projects/akshamala-erp/student/
com.example\:zkpush\:1.0.0=file:/home/sandip/Downloads/zkpush/
com.mycompany.jsf.crud\:jsf-crud\:1.0-SNAPSHOT=file:/home/sandip/NetBeansProjects/jsf-crud/
org.app\:PersonalFinanceTracker\:1.0-SNAPSHOT=file:/home/sandip/PersonalFinanceTrackerUsingServlet/
