replacepropsadd-multi-caret=false
replacepropsfind-backward-search=false
replacepropsfind-block-search=false
replacepropsfind-block-search-end=0
replacepropsfind-block-search-start=0
replacepropsfind-highlight-search=true
replacepropsfind-history=30
replacepropsfind-inc-search=true
replacepropsfind-match-case=true
replacepropsfind-preserve-case=false
replacepropsfind-reg-exp=false
replacepropsfind-smart-case=false
replacepropsfind-what=p:dataTable
replacepropsfind-whole-words=false
replacepropsfind-wrap-search=true
searchpropsadd-multi-caret=false
searchpropsfind-backward-search=false
searchpropsfind-block-search=false
searchpropsfind-highlight-search=false
searchpropsfind-history=30
searchpropsfind-inc-search=true
searchpropsfind-match-case=false
searchpropsfind-preserve-case=false
searchpropsfind-reg-exp=false
searchpropsfind-smart-case=false
searchpropsfind-what=sendemail
searchpropsfind-whole-words=false
searchpropsfind-wrap-search=false
