activeScanningScope=org.netbeans.modules.tasklist.impl.CurrentEditorScanningScope
dirtyCache=true
expanded_nb-tasklist-error=true
expanded_nb-tasklist-warning=false
folding_table_col_0=0.023972603
folding_table_col_1=0.65753424
folding_table_col_2=0.13767123
folding_table_col_3=0.18082191
groupTasksByCategory=true
sortingAscending=true
sortingColumn=1
table_col_0=0.010922993
table_col_1=0.5434189
table_col_2=0.20152922
table_col_3=0.2441289
