INSERT INTO attendance_device_command 
(`CREATED_DATE`,`STATUS`,`CREATED_BY_ADMIN`,
`COMMAND_STATUS`,`ATTENDANCE_DEVICE`,`COMMAND_TEXT`,`COMMAND_TYPE`)
VALUES(
    DATE_ADD(NOW(), INTERVAL 1 MINUTE),
    7,
    1,
    "PENDING",
    2,
    "SET OTPIONS DateTime 583080894",
    "SET_TIME"
);