org.netbeans.modules.jumpto.file.FileSearchPanel=noticeCreate;ApplicationConstant;noticeresour;createnotice;applica;applicat;notice;noticeTo;DatePatternConstant;noticeresource
org.netbeans.modules.jumpto.type.GoToPanel=
