org.netbeans.modules.jumpto.file.FileSearchPanel=registerschool;studentonlineadmissionco;registerschoo;studentonlineadmissiondto;registerschoolcollege;registersch;regi;registerSchoolCollege.css;form;utility
org.netbeans.modules.jumpto.type.GoToPanel=
