1=w
2=%s/InventoryItemSubGroup/InventorySubGroup/gc
3=%s
4=%s/inventoryItemDataModelJsf/inventoryItemController/gc
5=%s/inventoryItemBeanJsf/inventoryItemController/gc
6=write jk
7=write 
8=wq 
9=set nu
