1=growl
10=Edit
11=delete
12=\\<inventoryItemBeanJsf\\>
13=InventoryItemSubGroup
14=Delete
15=admin
16=authenti
17=Edkt
18=cache
19=dynamic
2=z
20=Jsf
21=jdf
22=manu
23=mana
24=manufac
25=manufacturedDate
26=manufa
27=adminAuthenticationBean
28=Manage
29=\\<inventoryItemSubGroupDataModelJsf\\>
3=itInventoryItemCode
30=Group
31=\\<inventoryItemDataModelJsf\\>
32=inventoryItemDataModelJsf
33=inventoryItemBeanJsf
34=EDit
35=inventoryGodownController
36=inventoryGo
37=godown
38=id
39=inventoryG
4=Method
40=immediate
41=inventoryItem
42=\\<inventoryItemOpeningDto\\>
43=btnSave
44=btnSAve
45=\\<inventoryGodownController\\>
46=edit
47=btnSa
48=viw
49=dlg
5=select
50=New
51=\\<frmCreateEdit\\>
52=Action
53=Act
54=Type
55=in
56=SAve
57=save
58=btn
59=manafacture
6=inventory
60=fit
61=fileView
62=action
63=Cancel
64=cancel
65=commandL
66=newxhtmlclass
67=new
68=Save
69=initCrea
7=Gender
70=java
8=invento
9=gender
IMPORT_CHECK_HACK=Fri Apr 17 10:41:45 NPT 2026
